pylev_s/task01
xthebat/iu4-2k24-python pull request #17
Opened 2024-02-27 19:48 UTC by pylevSt

2024-02-28 16:53 UTC, shadowk1337 requested changes
Идею не надо комитить

2024-03-19 17:52 UTC, pylevSt commented
Все поправил, когда примете?

2024-03-23 12:57 UTC, shadowk1337 requested changes

2024-03-23 12:57 UTC, shadowk1337 commented on .gitignore
> +/pylev_s/task01/.idea
Это зачем

2024-03-23 15:06 UTC, pylevSt commented on .gitignore
> +/pylev_s/task01/.idea
Не так конфликт решил, соре

2024-03-23 15:08 UTC, closed without merging