Bardik_e/task02
xthebat/iu4-2k24-python pull request #28
Opened 2024-03-01 16:15 UTC by bkeduu

2024-03-01 22:51 UTC, shadowk1337 requested changes
Вообще норм. Добавь тесты плиз, особенно на `list_dir`))

2024-03-01 22:51 UTC, shadowk1337 commented on bardik_e/task02/.gitignore
> +.idea
Все-таки лучше этот гитигнор вынести в свою общую папку, а не дублировать

2024-03-01 22:51 UTC, shadowk1337 commented on bardik_e/task02/src/task02.py
> +		nargs=1, help="Path to directory that will be recursively scanned.")
PEP8. Pylint ругнется тут

2024-03-01 22:51 UTC, shadowk1337 commented on bardik_e/task02/src/task02.py
> +		nargs=1, help="Maximum depth of tree.")
И тут ругнется

2024-03-01 22:51 UTC, shadowk1337 commented on bardik_e/task02/src/task02.py
> +	tree.run(args.path[0], int(args.depth[0] if isinstance(args.depth, list) else args.depth))
args.path[0] используется несколько раз, не лучше ли его вынести в отдельную переменную?

2024-03-01 22:51 UTC, shadowk1337 commented on bardik_e/task02/src/task02.py
> +	# call start function with this params
Как будто эти и выше коменты излишне. Вроде как и без них довольно понятно, что происходит

2024-03-01 22:51 UTC, shadowk1337 commented on bardik_e/task02/src/task02.py
> +	parser.add_argument("path", type=str, default=os.getcwd(),
Насколько я знаю, тут позиционный аргумент обязательный и нет смысла ему дефолтное значение выставлять

2024-03-01 22:51 UTC, shadowk1337 commented on bardik_e/task02/src/task02/tree.py
> +					print(Fore.GREEN, end="")
_Optional_
Для красоты окрашивание цветом можно вынести в отдельную функцию

2024-03-01 22:51 UTC, shadowk1337 commented on bardik_e/task02/src/task02/tree.py
> +					addition = BLANK
_Optional_
Возможно для уменьшения повторяемости тут лучше тернарный оператор

2024-03-01 22:51 UTC, shadowk1337 commented on bardik_e/task02/src/task02/tree.py
> +def list_dir(path: str, current_depth: int, start_depth: int, prefix: str) -> None:
Возможно тут лучше подойдет название функции, обозначающее, что в ней происходит

2024-03-02 04:54 UTC, bkeduu commented on bardik_e/task02/src/task02.py
> +		nargs=1, help="Path to directory that will be recursively scanned.")
Про это в курсе, как и про строчку ниже. Проблема в том, что даже pycharm автоматически не смог это отформатировать. Он выдаёт предупреждение либо о неправильном выравнивании (как в этом варианте), либо о смешивании табов и пробелов. Пробовал с настройками оформления в части форматирования поиграться, но не получилось, все равно одно из этих двух замечаний присутствует

2024-03-02 04:56 UTC, bkeduu commented on bardik_e/task02/src/task02.py
> +	parser.add_argument("path", type=str, default=os.getcwd(),
На убунте от . строит дерево, если путь не задан

2024-03-02 04:59 UTC, bkeduu commented
> Вообще норм. Добавь тесты плиз, особенно на `list_dir`))

А что там тестить?) Оно же даже не возвращает ничего. Просто потыкать какие-нибудь дефолтные пути в зависимости от ОС, чтобы оно эксепшены не кидало, можно?

2024-03-02 05:01 UTC, bkeduu commented on bardik_e/task02/src/task02.py
> +	tree.run(args.path[0], int(args.depth[0] if isinstance(args.depth, list) else args.depth))
А в чём проблема с ним? Это ж не вызов функции, а просто извлечение элемента из листа по константному индексу

2024-03-02 14:22 UTC, xthebat commented
> > Вообще норм. Добавь тесты плиз, особенно на `list_dir`))
> 
> А что там тестить?) Оно же даже не возвращает ничего. Просто потыкать какие-нибудь дефолтные пути в зависимости от ОС, чтобы оно эксепшены не кидало, можно?

Ну по хорошему нужно замокировать файловую систему и протестить всю функциональность написанной либы. Но мокирование мы не проходили, поэтому можно сделать, чтобы функция принимала делегат как получать список путей в директории например и прокинуть ему делегат. Протестить окрашивание например тоже можно. А целом да - "Просто потыкать какие-нибудь дефолтные (замокированные) пути" и проверить, что дерево строится правильно. Тесты пишутся в том числе для того, чтобы в будущем быть уверенным, что ничего не сломано, если потребуются изменения в коде.

2024-03-03 14:00 UTC, shadowk1337 commented on bardik_e/task02/src/task02.py
> +	tree.run(args.path[0], int(args.depth[0] if isinstance(args.depth, list) else args.depth))
Проблема в том, что это дублирование кода. Гораздо лучше вынести это в отдельную переменную и при надобности менять значение только в ней, а не во всех вызовах `args.path[0]`

2024-03-06 15:31 UTC, xthebat requested changes

2024-03-06 15:31 UTC, xthebat commented on bardik_e/task02/src/task02.py
> +
Зачем?

2024-03-06 15:31 UTC, xthebat commented on bardik_e/task02/src/task02/tree.py
> +
Зачем?

2024-03-06 15:31 UTC, xthebat commented on bardik_e/task02/src/task02/tree.py
> +def run(path: str, depth: int) -> None:
None указывать не нужно, если ничего не возвращает

2024-03-06 15:31 UTC, xthebat commented on bardik_e/task02/src/task02/tree.py
> +			# else, iterating over directory items
В отдельную функцию

2024-03-06 15:31 UTC, xthebat commented on bardik_e/task02/src/task02.py
> +	tree.run(args.path[0], int(args.depth[0] if isinstance(args.depth, list) else args.depth))
Если принять, что этот код "чувствителен" к быстродействию, то на питоне это работает не так как в С или С++. В данном случае каждый раз будет вызываться поиск атрибута path у класса args, после этого __getitem__, что может просадить быстродействие. В некоторых в питоне случаях специально кешируют методы в локальные переменные в случае, если к ним идет обращение в цикле.

2024-03-06 15:31 UTC, xthebat commented on bardik_e/task02/src/task02/tree.py
> +	if (start_depth < 0) or (start_depth > 0 and (start_depth - current_depth)):
скобки не нужны

2024-03-10 09:43 UTC, xthebat approved these changes
5/3

2024-03-10 09:43 UTC, merged