new file:   Nurumov_r/task02/task02.py
xthebat/iu4-2k24-python pull request #29
Opened 2024-03-02 00:46 UTC by robnur

Не банте за 32 строчку пожалуйста
Полагаю реализация этого проекта предполагалась другая но мне в голову пришла такая, согласен немного с костылями но зато с изюминкой

2024-03-02 00:54 UTC, robnur commented
возможно мне придется все оформить в пакет с src tests итд но я пока не понял как мне это сделать в vs code, так же на PEP8 я не проверял, только визуально

2024-03-02 09:53 UTC, xthebat requested changes
Кроме указанных недочетов, отсутствуют тесты

2024-03-02 09:53 UTC, xthebat commented on Nurumov_r/task02/task02.py
> +from os import listdir
всё из os обычно импортируют без раскрытия namespace

2024-03-02 09:53 UTC, xthebat commented on Nurumov_r/task02/task02.py
> +def tree(lvl:int, path:str):
не соответствует PEP8

2024-03-02 09:53 UTC, xthebat commented on Nurumov_r/task02/task02.py
> +        if isdir(f"{path}/{e}"):
Объединение путей необходимо делать через os.path.join или использовать Path

2024-03-02 09:53 UTC, xthebat commented on Nurumov_r/task02/task02.py
> +    for e in sorted(arr):
Название переменной неудачное и непонятно, что означает

2024-03-02 09:53 UTC, xthebat commented on Nurumov_r/task02/task02.py
> +    for e in sorted(arr):
arr, почему не array? Не используйте бессмысленные сокращения

2024-03-02 09:53 UTC, xthebat commented on Nurumov_r/task02/task02.py
> +def print_result(arrays, lvl):
нет аннотации типов

2024-03-02 09:53 UTC, xthebat commented on Nurumov_r/task02/task02.py
> +    lvl = lvl - 1
аналогично ниже - сокращения в называниях переменных

2024-03-02 09:53 UTC, xthebat commented on Nurumov_r/task02/task02.py
> +            if "\033[34m" in e:
константы выносим в начало функции или файла с именем

2024-03-02 09:53 UTC, xthebat commented on Nurumov_r/task02/task02.py
> +            print(lvl * "   " + e)
склейка строк - необходимо избавиться от неё

2024-03-02 09:53 UTC, xthebat commented on Nurumov_r/task02/task02.py
> +def print_result(arrays, lvl):
Функция print делает, что-то ещё кроме как print.
Зона ответственности функций должна быть согласна их названию и не выходить за её рамки.

2024-03-02 09:53 UTC, xthebat commented on Nurumov_r/task02/task02.py
> +        else:
Кажется, что можно использовать elif (забыл про него сказать на стриме)

2024-03-02 09:53 UTC, xthebat commented on Nurumov_r/task02/task02.py
> +def print_result(arrays, lvl):
Выглядит, так что структуризация кода - неудачная. Должно быть как минимум две функции - одна собирает директории/файлы по заданной корневой директории в некую коллекцию (какую выбор за Вами). Вторая обходит её и выводит в заданный поток вывода с минимальной накрученной поверх логикой.

2024-03-02 09:53 UTC, xthebat commented on Nurumov_r/task02/task02.py
> +    print("\033[0m{}".format(f"\n{count[0]} directories, {count[1]} files"))
Magic'и в коде + формат смешанный с интерполяцией строк... Используем только интерполяцию строк для форматирования. Либо в обоснованных случаях что-то другое

2024-03-02 09:53 UTC, xthebat commented on Nurumov_r/task02/task02.py
> +    mass = tree(lvl, path)
Для чего здесь масса? Что это такое? ... Вообще это максимально неудачный нейминг. Сокращение + транслит. Используем только полное наименование без транслита.

2024-03-02 09:53 UTC, xthebat commented on Nurumov_r/task02/task02.py
> +
Нарушение PEP8

2024-03-02 09:53 UTC, xthebat commented on Nurumov_r/task02/task02.py
> +    elements = []
нет аннотации - это список чего

2024-03-02 09:53 UTC, xthebat commented on Nurumov_r/task02/task02.py
> +    main(3,"./")
Не используется sys.argv

2024-03-02 10:01 UTC, robnur commented on Nurumov_r/task02/task02.py
> +def print_result(arrays, lvl):
Я хотел показать знание рекурсий(

2024-03-02 10:16 UTC, robnur commented on Nurumov_r/task02/task02.py
> +def print_result(arrays, lvl):
я правильно понял что вам не понравилась реализация? В функции tree я прохожу по директориям и записываю в массив все найденные директории и файлы (помечая их разными цветами) учитывая заданный уровень вложенности. В print_reult я вывожу все элементы массива подсчитывая директории и файлы (различать их я могу благодаря цвету), склейка строк мне нужна потому что я не знаю как еще можно использовать умножение строк, которое необходимо для визуального различия между разными уровнями вложенности

2024-03-02 10:19 UTC, robnur commented on Nurumov_r/task02/task02.py
> +            print(lvl * "   " + e)
как тогда реализовать умножение строк чтобы отобразить уровень вложенности

2024-03-02 10:20 UTC, robnur commented on Nurumov_r/task02/task02.py
> +            if "\033[34m" in e:
я не понимаю про какую константу вы говорите

2024-03-02 10:22 UTC, robnur commented on Nurumov_r/task02/task02.py
> +    print("\033[0m{}".format(f"\n{count[0]} directories, {count[1]} files"))
в данном случае не придумал как иначе сбросить стили и сделать вывод белым

2024-03-02 11:03 UTC, robnur commented
Поправил что понял, проверку на PEP8 сделал, названия поменял, от склеек избавился

2024-03-02 14:08 UTC, xthebat commented on Nurumov_r/task02/src/task02.py
> +                elements.insert(0, collect_tree(
120 символов длина строки по PEP8

2024-03-02 14:08 UTC, xthebat commented on Nurumov_r/task02/task02.py
> +    print("\033[0m{}".format(f"\n{count[0]} directories, {count[1]} files"))
Вынести Magic-и в переменные

2024-03-02 14:11 UTC, xthebat commented on Nurumov_r/task02/src/task02.py
> +                elements.insert(0, collect_tree(
120 символов на строку

2024-03-02 14:11 UTC, xthebat commented
Это не исправлено
- отсутствуют тесты
- структуризация кода - не соответствует указанной на стриме
- PR должен быть выполнен с того аккаунта, который указан в Excel таблице

2024-03-02 14:22 UTC, robnur commented on Nurumov_r/task02/src/task02.py
> +                elements.insert(0, collect_tree(
я не понимаю о чем речь

2024-03-02 14:23 UTC, robnur commented on Nurumov_r/task02/task02.py
> +    print("\033[0m{}".format(f"\n{count[0]} directories, {count[1]} files"))
вы про это \033[0m{} ?

2024-03-03 14:16 UTC, shadowk1337 requested changes
Нужно доделать логику и вывод команды. На данный момент команда не соответствует алгоритму работы команды `tree`:
- не выводится название директории от которой идет поиск
- не выводятся символы, обозначающие визуальную иерархию объектов в директории

2024-03-03 14:16 UTC, shadowk1337 commented on Nurumov_r/task02/src/task02.py
> +    lvl = lvl - 1
```python
lvl -= 1
```

2024-03-03 14:16 UTC, shadowk1337 commented on Nurumov_r/task02/src/task02.py
> +                elements.insert(0, collect_tree(
Речь о том, что PEP8 подразумевает, что в строке может быть до 120 символов, необязятельно тут переносить на следующую строку

2024-03-03 14:16 UTC, shadowk1337 commented on Nurumov_r/task02/src/task02.py
> +            elements.insert(0, f"\033[34m{element}")
Константы надо выносить, про это писали

2024-03-03 14:16 UTC, shadowk1337 commented on Nurumov_r/task02/src/task02.py
> +            lvl += 1
ы? Зачем тут плюсовать, а в 29 строке минусовать `lvl`, если можно `tree` вызывать сразу как
```python
tree(element, lvl + 1)
```

2024-03-03 14:16 UTC, shadowk1337 commented on Nurumov_r/task02/src/task02.py
> +def tree(arrays: list, lvl: int):
Нет типа возвращаемого значения

2024-03-03 14:16 UTC, shadowk1337 commented on Nurumov_r/task02/src/task02.py
> +            if "\033[34m" in element:
Полагаться, на наличие такого символа вряд ли стоит. Окрашивание строк может убраться, тогда как определять, что `element` директория?

2024-03-03 14:16 UTC, shadowk1337 commented on Nurumov_r/task02/task02.py
> +    print("\033[0m{}".format(f"\n{count[0]} directories, {count[1]} files"))
Да, про это

2024-03-03 14:16 UTC, shadowk1337 commented on Nurumov_r/task02/task02.py
> +            if "\033[34m" in e:
`"\033[34m"`

2024-03-03 14:17 UTC, shadowk1337 commented on Nurumov_r/task02/task02.py
> +            print(lvl * "   " + e)
джоин

2024-03-03 14:18 UTC, shadowk1337 commented on Nurumov_r/task02/task02.py
> +def print_result(arrays, lvl):
Надо переделать структуру кода: выделить компонент, который отвечает за вывод, и выделить компонент, который отвечает за обработку объектов в директории и составляет их иерархию

2024-03-03 14:21 UTC, robnur commented on Nurumov_r/task02/src/task02.py
> +            lvl += 1
не подумал

2024-03-03 14:24 UTC, robnur commented on Nurumov_r/task02/src/task02.py
> +            if "\033[34m" in element:
мне пушить в массив вместо элемента массив где [0] это название файла/директории, а в [1] тип (файл это или директория)?

2024-03-03 14:26 UTC, robnur commented
про 120 символов, документ сам так отформатировался под PEP8, могу конечно руками поправить но полагаю что если в следующий раз я снова отформатирую то могу забыть и будет снова такой перенос

2024-03-03 14:27 UTC, robnur commented on Nurumov_r/task02/src/task02.py
> +            elements.insert(0, f"\033[34m{element}")
константы вы имеете ввиду "новый" путь?

2024-03-03 14:27 UTC, robnur commented on Nurumov_r/task02/src/task02.py
> +    lvl = lvl - 1
не заметил, поправлю

2024-03-03 14:30 UTC, robnur commented
> Это не исправлено
> 
> * отсутствуют тесты
> * структуризация кода - не соответствует указанной на стриме
> * PR должен быть выполнен с того аккаунта, который указан в Excel таблице

тесты еще сделаю
про структуризацию кода не совсем понял, где можно посмотреть примеры? стрим я не записывал
аккаунт в таблице поправил

2024-03-03 14:32 UTC, robnur commented on Nurumov_r/task02/src/task02.py
> +            if "\033[34m" in element:
да и я не совсем понимаю как оно может убраться до вывода если оно хранится в массиве. как по мне проверка на файл или директорию по цвету рациональное решение хоть и не совсем понятное, могу комментарии написать

2024-03-03 14:40 UTC, shadowk1337 commented
> стрим я не записывал

в дискорде есть ссылка на запись лекции.......

2024-03-03 14:41 UTC, shadowk1337 commented on Nurumov_r/task02/src/task02.py
> +            elements.insert(0, f"\033[34m{element}")
`\033[34m`

2024-03-03 17:12 UTC, robnur commented
> > стрим я не записывал
> 
> в дискорде есть ссылка на запись лекции.......

Не заметил сразу, искал в новых сообщениях

2024-03-04 09:08 UTC, robnur commented
Короче переписал весь код

2024-03-04 11:04 UTC, shadowk1337 commented on Nurumov_r/task02/src/task02/tree.py
> +red = '\033[31m'
Названия констант заглавными символами

2024-03-04 11:06 UTC, shadowk1337 commented on Nurumov_r/task02/src/task02/tree.py
> +            if lvl < 0:
сокращения в названиях переменных

2024-03-04 11:07 UTC, shadowk1337 commented on Nurumov_r/task02/src/task02/tree.py
> +    global directories_count, files_count
Глобальные переменные - плохо, зачем они тебе тут?

2024-03-04 11:14 UTC, shadowk1337 commented on Nurumov_r/task02/src/task02/tree.py
> +        try:
К чему этот try?

2024-03-04 11:15 UTC, shadowk1337 commented on Nurumov_r/task02/src/task02/tree.py
> +def tree(directory: str, max_depth: int = 0, depth: int = 0, indent: str = ''):
Как правило, названия функций содержат глагол

2024-03-04 11:16 UTC, shadowk1337 commented on Nurumov_r/task02/src/task02/tree.py
> +            print(f"{white}{indent}{last}{blue}{item}")
Надо разделить обход директории и вывод в консоль

2024-03-04 11:17 UTC, shadowk1337 commented on Nurumov_r/task02/src/task02/tree.py
> +            tree(path, max_depth, depth + 1, f"{indent}{branch}")
Тут явное дублирование кода, такого лучше избегать

2024-03-04 11:17 UTC, shadowk1337 commented on Nurumov_r/task02/src/task02/tree.py
> +            print(f"{white}{indent}{tee}{green}{item}")
дублирование кода

2024-03-04 14:33 UTC, robnur commented
Вроде все поправил, я так понимаю осталось тесты сделать

2024-03-04 15:00 UTC, shadowk1337 commented
> Вроде все поправил, я так понимаю осталось тесты сделать

Остались незарезолвленные комментарии

2024-03-04 15:08 UTC, robnur commented
> > Вроде все поправил, я так понимаю осталось тесты сделать
> 
> Остались незарезолвленные комментарии

я не нахожу какие именно

2024-03-11 15:59 UTC, robnur commented
Вроде выполнил все условия, в том числе и дополнительные

2024-03-12 15:06 UTC, xthebat approved these changes
5/3

2024-03-12 15:07 UTC, merged