novikov_t/task02
xthebat/iu4-2k24-python pull request #31
Opened 2024-03-02 17:35 UTC by SARWX

пример вызова из командной строки: 
python tree.py ../ -L 3

2024-03-03 14:38 UTC, shadowk1337 requested changes
Помимо недочетов стоит пересмотреть структуру кода: надо выделить часть, которая обрабатывает директорию и часть, которая выводит результат в консоль.

2024-03-03 14:38 UTC, shadowk1337 commented on novikov_t/task02/src/tree.py
> +
PEP8: два отступа

2024-03-03 14:38 UTC, shadowk1337 commented on novikov_t/task02/src/tree.py
> +            print(decor_prefix + "\\-- " + item)
Все константые значения нужно вынести в константы

2024-03-03 14:38 UTC, shadowk1337 commented on novikov_t/task02/src/tree.py
> +    i = 0                       # index of the current item
Си стайл, для таких циклов есть `enumerate`. Тут не надо использовать `i`

2024-03-03 14:38 UTC, shadowk1337 commented on novikov_t/task02/src/tree.py
> +        print(cur_dir)
Все-таки не стоит в одной функции мешать и обработку директории, и вывод в консоль. Лучше разделить эти компоненты на разные функции. В этой функции формировать иерархию файлов в директории, а в другой функции выводить ее в консоль.

2024-03-03 14:38 UTC, shadowk1337 commented on novikov_t/task02/src/tree.py
> +def generate_tree(directory, req_depth, current_depth = 1, decor_prefix=""):
А вообще название функции подразумевает, что она что-то выводит в консоль?

2024-03-03 14:38 UTC, shadowk1337 commented on novikov_t/task02/src/tree.py
> +            print(decor_prefix + "|-- " + item)
Конкатенация строк довольно ресурсозатратная операция, при каждой конкатенации у тебя выделяется новая память под строку. Лучше все-таки обойтись без нее тут

2024-03-03 14:38 UTC, shadowk1337 commented on novikov_t/task02/src/tree.py
> +        print(cur_dir)
Это можно упростить тернарным оператором

2024-03-03 14:38 UTC, shadowk1337 commented on novikov_t/task02/src/tree.py
> +                new_decor_prefix = decor_prefix + "|   "
Это можно упростить тернарным оператором

2024-03-03 14:38 UTC, shadowk1337 commented on novikov_t/task02/src/tree.py
> +        # check if current item is directory
Комментраий ни к чему, и так понятно

2024-03-03 14:38 UTC, shadowk1337 commented on novikov_t/task02/src/tree.py
> +            # recursive call of the generate_tree() function
Понятно.

2024-03-03 14:38 UTC, shadowk1337 commented on novikov_t/task02/tests/referents/referent_2.txt
> +    \-- file3.txt
А разве такой вывод соответствует выводу команды `tree`?

2024-03-03 21:00 UTC, SARWX commented
Исправил:

- разбил исходную функцию generate_tree() на generate_tree() и print_tree();
- воспользовался для получения индекса элемента функцией enumerate();
- исправил ошибку с некорректным отображением структуры каталогов;
- заменил символы, используемые для отображения структуры на те, что используются в команде tree;
- по возможности использовал тернарный оператор вместо _if: ... else: ..._ ;

2024-03-04 12:39 UTC, shadowk1337 approved these changes
Sum 3/3

2024-03-04 12:40 UTC, merged