Analog of the tree command
xthebat/iu4-2k24-python pull request #35
Opened 2024-03-04 09:38 UTC by natindo

2024-03-04 14:51 UTC, shadowk1337 requested changes
Нужно исправить коменты и сделать тесты

2024-03-04 14:51 UTC, shadowk1337 commented on Lyskov_D/task02/scripts/tree.py
> +def tree(startPath: str, maxLevel: int):
PEP8: названия переменных должны быть в snake_case

2024-03-04 14:51 UTC, shadowk1337 commented on Lyskov_D/task02/scripts/tree.py
> +def tree(startPath: str, maxLevel: int):
Как правило, название функций содержит глагол. Из текущего названия вообще не понятно, что она делает

2024-03-04 14:51 UTC, shadowk1337 commented on Lyskov_D/task02/scripts/flags.py
> +parser.add_argument('nest', type=int, help='nesting')
`nest` не должен быть обязательным аргументом, если он не задан нужно выводить названия рекурсивно до конца

2024-03-04 14:51 UTC, shadowk1337 commented on Lyskov_D/task02/README.MD
> +The tests were not applied because the functions do not return any values
То что функция ничего не возвращает не значит, что ее нельзя протестировать. Для тестирования таких функций можно, к примеру, использовать мокирование каких-либо объектов в функции. В данном случае функцию `tree` следует разделить на часть, которая отвечает за обработку директории (ее легко можно будет тогда протестировать по возвращаемому значению) и часть, которая выводит результат прошлой части в консоль

2024-03-12 10:51 UTC, natindo commented
Ещё у меня в табличке не отмечен 1 таск, хотя я сдал его вовремя (признаю, назвал ПР не правильно, зачтите плиииз)

2024-03-12 15:12 UTC, xthebat commented on Lyskov_D/task02/scripts/tree.py
> +init(autoreset=True)
лучше colorama.init()

2024-03-12 15:13 UTC, xthebat commented on Lyskov_D/task02/README.MD
> +The tests were not applied because the functions do not return any values
Комментарий в README.MD не соответствует реальности

2024-03-12 15:14 UTC, xthebat approved these changes
5/3 

Обрати внимание на комменты

2024-03-12 15:14 UTC, merged