kiselev_p/task02
xthebat/iu4-2k24-python pull request #36
Opened 2024-03-04 21:28 UTC by kiselpd

2024-03-04 21:30 UTC, kiselpd commented
Для тестирования создал виртуальные директории и файлы, подменил параметры командной строки при вызове скрипта, перенаправил stdout в string и сравнил. Есть ли какой-то еще способ, возможно как легче сделать тесты?

2024-03-10 09:52 UTC, xthebat requested changes

2024-03-10 09:52 UTC, xthebat commented on kiselev_p/task02/src/tree/tree.py
> +    def __printDir(self, path : str, tmp_depth : int = 0, prefix : str = "") -> None:
нарушение PEP8

2024-03-10 09:52 UTC, xthebat commented on kiselev_p/task02/src/tree/tree.py
> +    def __printName(self, prefix : str, abs_path : str) -> None:
Нарушение PEP8

2024-03-10 09:52 UTC, xthebat commented on kiselev_p/task02/src/tree/tree.py
> +        parser = ArgumentParser(description="Build tree of filesystem")
Парсер аргументов должен быть отделен от класса, который строит дерево

2024-03-10 09:52 UTC, xthebat commented on kiselev_p/task02/test/test_tree.py
> +test_dir = os.path.dirname(__file__)
Лучше использовать временную директорию https://docs.python.org/3/library/tempfile.html

2024-03-10 09:52 UTC, xthebat commented on kiselev_p/task02/test/test_tree.py
> +def cmp_expected_and_real(suite : str, capsys, create_filesystem) ->None:
обычно expected и actual

2024-03-10 09:52 UTC, xthebat commented on kiselev_p/task02/test/test_tree.py
> +def cmp_expected_and_real(suite : str, capsys, create_filesystem) ->None:
нарушение PEP8

2024-03-10 09:52 UTC, xthebat commented on kiselev_p/task02/test/test_tree.py
> +    with open(os.path.join(test_dir, "suites", suite), "r") as f:
Маджики в коде лучше выносить в начало в константы

2024-03-10 09:52 UTC, xthebat commented on kiselev_p/task02/test/test_tree.py
> +    cmp_expected_and_real("test_tree_depth.txt", capsys, create_filesystem)
Имя файла в начало в константы

2024-03-10 09:52 UTC, xthebat commented on kiselev_p/task02/test/test_tree.py
> +    cmp_expected_and_real("test_tree_desc.txt", capsys, create_filesystem)
Аналогично по имени файла

2024-03-10 09:52 UTC, xthebat commented on kiselev_p/task02/test/test_tree.py
> +def test_tree(create_filesystem, monkeypatch, capsys):
Выглядит так, что эти тесты можно сделать через параметризацию

2024-03-20 00:09 UTC, kiselpd commented
Исправил
[fix kiselev_p/task02](https://github.com/xthebat/iu4-2k24-python/pull/36/commits/06409f73f3642d0e5818b09d4214799e6a8599dc)

2024-03-23 12:48 UTC, shadowk1337 approved these changes
Base: 3/3
Color + 1
Sum: 4

2024-03-23 12:55 UTC, merged