Create volk task02. It is hard
xthebat/iu4-2k24-python pull request #39
Opened 2024-03-05 17:30 UTC by Volkolakk

2024-03-06 16:17 UTC, xthebat requested changes

2024-03-06 16:17 UTC, xthebat commented on volkov_g/task02/src/task02/main.py
> +            i = depth-1
Нарушение PEP8

2024-03-06 16:17 UTC, xthebat commented on volkov_g/task02/src/task02/main.py
> +def function_sample(x: int, y: int) -> int:
Не используемая функция

2024-03-06 16:17 UTC, xthebat commented on volkov_g/task02/src/task02/main.py
> +def dir_control(putin: str = None, depth: int = 1, skip: int = 0, skip_stick: int = 0) -> int:
Неудачное название функции

2024-03-06 16:17 UTC, xthebat commented on volkov_g/task02/src/task02/main.py
> +def dir_control(putin: str = None, depth: int = 1, skip: int = 0, skip_stick: int = 0) -> int:
Нет разделение логики работы функций

2024-03-06 16:17 UTC, xthebat commented on volkov_g/task02/test/test_py.py
> +    assert function_sample(1, 2) == 3
Для чего?

2024-03-06 16:17 UTC, xthebat commented on volkov_g/task02/src/task02/main.py
> +# putin - path of start (put in)
Должно быть оформлено через docstring

2024-03-06 16:17 UTC, xthebat commented on volkov_g/task02/src/task02/main.py
> +        # {'└' * ( 1 if skip > 0 else 0)}
Мертвый код - убираем

2024-03-11 09:26 UTC, Volkolakk commented on volkov_g/task02/test/test_py.py
> +    ]
Пустые папки не перенеслись , поэтому для тестов надо поменять  folders и file

2024-03-12 15:23 UTC, xthebat commented on volkov_g/task02/test/requirements.txt
> +os
Встроенный модуль

2024-03-12 15:24 UTC, xthebat commented on volkov_g/task02/test/requirements.txt
> +colorama
Желательно указывать версию ~=

2024-03-12 15:24 UTC, xthebat commented on volkov_g/task02/src/task02/main.py
> +
Пустые строки не нужны

2024-03-12 15:24 UTC, xthebat commented on volkov_g/task02/src/task02/main.py
> +            if (list_tree[check_drench] % 1000) >= (list_tree[count_drench] % 1000):
Желательно разбить на функции

2024-03-12 15:25 UTC, xthebat commented on volkov_g/task02/src/task02/main.py
> +colorama.init()
Две пустые строки после импортов

2024-03-12 15:25 UTC, xthebat commented on volkov_g/task02/src/task02/main.py
> +tree_print(tree_dir("test folders", 3))
Нет main-a

2024-03-12 15:25 UTC, xthebat commented on volkov_g/task02/test/test_py.py
> +# import os
Мертвый код

2024-03-12 15:27 UTC, xthebat commented on volkov_g/task02/src/task02/main.py
> +    for count_drench in range(2, len(list_tree), 2):
Что такое drench?

2024-03-12 15:28 UTC, xthebat approved these changes
+1/3 - база (очень много недочетов, если хочешь можешь поправить, пока мерджить не буду)
+1 - за цвет
+1 - за кол-во

2024-03-23 12:47 UTC, merged