task01
xthebat/iu4-2k24-python pull request #4
Opened 2024-02-24 12:28 UTC by natindo

2024-02-26 12:30 UTC, shadowk1337 requested changes

2024-02-26 12:30 UTC, shadowk1337 commented on .gitignore
> +.DS_Store
Не надо редачить общий гитигнор плиз

2024-02-27 10:47 UTC, natindo commented on .gitignore
> +.DS_Store
А как ещё можно выкинуть все системные папки от macos?

2024-02-27 15:39 UTC, shadowk1337 commented on .gitignore
> +.DS_Store
Не коммитить -_-. Общий гитигнор не надо редачить, если кто-то еще его поменяет, то возникнет конфликт.  Также можешь создать в своей папке гитигнор и там добавлять исключения

2024-02-27 15:45 UTC, shadowk1337 commented on .gitignore
> +.DS_Store
Во, вот тут пример: https://github.com/xthebat/iu4-2k24-python/pull/3/files

2024-02-28 17:02 UTC, shadowk1337 approved these changes
Sum: 3/3

2024-02-28 17:03 UTC, merged