task01
xthebat/iu4-2k24-python pull request #40
Opened 2024-03-05 18:46 UTC by sladost1

2024-03-10 09:32 UTC, xthebat requested changes
Структура директорий некорректна

2024-03-10 09:32 UTC, xthebat commented on petrichenko_d/task01/main.py
> +z1
Для чего это?

2024-03-10 09:32 UTC, xthebat commented on petrichenko_d/task01/main.py
> +    a = 10
Внутри `if __name__ == "__main__":` должен быть только вызов main

2024-03-23 12:45 UTC, shadowk1337 approved these changes
Sum: 2/3

2024-03-23 12:46 UTC, merged