bubnov_v/task02
xthebat/iu4-2k24-python pull request #44
Opened 2024-03-06 09:05 UTC by newUrbanrustic

2024-03-10 09:55 UTC, xthebat requested changes
Решение очень напоминает вариант Нурумова

2024-03-10 09:55 UTC, xthebat commented on bubnov_v/task01/additions/add.py
> -from sys import platform
Зачем эти файлы были удалены?

2024-03-10 09:55 UTC, xthebat commented on bubnov_v/task02/src/main.py
> +    # Start function "tree"
Бесполезный коммент

2024-03-10 09:55 UTC, xthebat commented on bubnov_v/task02/src/main.py
> +# Creating a parser for incoming arguments and options
Аналогично, коммент бесполезный

Если очень хочется - можно сделать docstring для функции, но такие комменты не имеют смысла

2024-03-10 09:55 UTC, xthebat commented on bubnov_v/task02/src/tree.py
> +            item = create_tree(path, level - 1)
Нет разделение логики сбора данных и их вывода

2024-03-10 12:59 UTC, newUrbanrustic commented on bubnov_v/task02/src/tree.py
> +            item = create_tree(path, level - 1)
На сбор данных функция create_tree, от которой мы получаем массив, в котором содержатся названия папок и файлов, для вывода данных функция output_tree

2024-03-10 12:59 UTC, newUrbanrustic commented on bubnov_v/task01/additions/add.py
> -from sys import platform
Там менял название функции с osIs на os_is, чтобы по pep8 было, а удалил так как увидел, что функции можно называть как было до то есть osIs

2024-03-10 12:59 UTC, newUrbanrustic commented on bubnov_v/task02/src/tree.py
> +            item = create_tree(path, level - 1)
Добавил функции check_element и count_elements для разделения логики

2024-03-10 13:10 UTC, newUrbanrustic reviewed
Update task02

2024-03-10 14:28 UTC, xthebat requested changes
Есть не резолвленные коменты

2024-03-10 14:28 UTC, xthebat commented on bubnov_v/task02/src/tree.py
> +        if type(item) is list:
isinstance

2024-03-11 18:50 UTC, newUrbanrustic commented
Add docstring and change type() to isinstanse()

2024-03-12 15:09 UTC, xthebat approved these changes
5/3

2024-03-12 15:09 UTC, merged