Task02
xthebat/iu4-2k24-python pull request #45
Opened 2024-03-06 15:23 UTC by sempoinf

2024-03-10 09:40 UTC, xthebat commented
Укажите правильное название PR

2024-03-10 09:56 UTC, xthebat requested changes
Укажите правильное название PR

2024-03-11 15:34 UTC, sempoinf commented
а дайте пожалуйста подсказку, что именно не правильно написано?

2024-03-12 15:22 UTC, xthebat requested changes

2024-03-12 15:22 UTC, xthebat commented on yakimov_a/task02/scr/main.py
> +sys.path.append('/Users/yaao20u291/Library/Mobile Documents/com~apple~CloudDocs/code/Python/iu4-2k24-python/iu4-2k24-python/yakimov_a/task02')
Это не будет работать на других машинах (путь есть только у тебя)

2024-03-12 15:22 UTC, xthebat commented on yakimov_a/task02/scr/main.py
> +sys.path.append('/Users/yaao20u291/Library/Mobile Documents/com~apple~CloudDocs/code/Python/iu4-2k24-python/iu4-2k24-python/yakimov_a/task02')
Pycharm автоматически добавляет пути в sys.path если делать как рассказывал на стриме

2024-03-12 15:22 UTC, xthebat commented on yakimov_a/task02/scr/main.py
> +# from ..scripts.arg_parser import args
Мертвый код убираем либо указываем комментариями зачем он нужен

2024-03-12 15:22 UTC, xthebat commented on yakimov_a/task02/scripts/tree.py
> +# def main():
Аналогично про мертвый код

2024-03-12 15:22 UTC, xthebat commented on yakimov_a/task02/testpy/testik_gen_tree.py
> +# import os
Снова мертвый код

2024-03-12 15:22 UTC, xthebat commented on yakimov_a/task02/testpy/testiki_gen+print.py
> +    # Захватываем стандартный вывод
Эти комментария - часть документации... они не нужны

2024-03-12 15:22 UTC, xthebat commented on yakimov_a/task02/testpy/testiki_gen+print.py
> +sys.path.append('/Users/yaao20u291/Library/Mobile Documents/com~apple~CloudDocs/code/Python/iu4-2k24-python/iu4-2k24-python/yakimov_a/task02')
Не будет работать нигде кроме твоего компьютера

2024-03-12 15:22 UTC, xthebat commented on yakimov_a/task02/testpy/testiki_gen+print.py
> +    # Тестируем функцию print_tree
Локализованнные комментарии - нежелательны

2024-03-12 15:22 UTC, xthebat commented on yakimov_a/task02/testpy/testiki_gen+print.py
> +
Не соответствует PEP8 (1 строка в конце файла)

2024-03-12 15:22 UTC, xthebat commented on yakimov_a/task02/testpy/testik_gen_tree.py
> +
Не соответствует PEP8

2024-03-12 15:22 UTC, xthebat commented on yakimov_a/task02/scr/main.py
> +import argparse as argp
зачем этот as? сокращение переменных - нежелательно, так ещё и вводим в заблуждение, что это за модуль. argparse известное каждому кто прогал на питоне

2024-03-12 15:22 UTC, xthebat commented on yakimov_a/task02/scr/main.py
> +    # print_tree(gen_tree(args.path, args.lvl))
Мертвый код

2024-03-12 15:22 UTC, xthebat commented on yakimov_a/task02/scr/main.py
> +if __name__ == '__main__':
Папка src названа с опечаткой

2024-03-23 12:44 UTC, shadowk1337 requested changes

2024-03-23 12:44 UTC, shadowk1337 commented on .gitignore
> +.DS_Store
Это надо убрать отсюда

2024-03-27 09:06 UTC, shadowk1337 commented on .gitignore
> +gladkikh_a/sem02/.idea/
нужно вообще убрать изменение из этого файла

2024-04-02 14:58 UTC, merged