gushchin_g/task02
xthebat/iu4-2k24-python pull request #47
Opened 2024-03-06 16:47 UTC by GushchinGleb

Add counters for directories and files.

2024-03-10 10:15 UTC, xthebat requested changes

2024-03-10 10:15 UTC, xthebat commented on gushchin_g/task02/requirements.txt
> -importlib-metadata==3.4.0
Зачем?

2024-03-10 10:15 UTC, xthebat commented on gushchin_g/task02/src/task02/task02.py
>  from typing import List
Это из python3.8, в python3.11 можно использовать сами типы для аннотаций

2024-03-10 10:15 UTC, xthebat commented on gushchin_g/task02/src/task02/task02.py
>      dirrectory_iterator: int = 0
Typo: dirrectory -> directory

2024-03-10 10:15 UTC, xthebat commented on gushchin_g/task02/src/task02/task02.py
> +    scan_dirrectory_result: Tuple[str, int, int] = scan_dirrectory(
Typo: dirrectory -> directory

2024-03-23 12:39 UTC, shadowk1337 approved these changes
+1

2024-03-23 12:39 UTC, merged