taralo_a/task02
xthebat/iu4-2k24-python pull request #48
Opened 2024-03-06 17:16 UTC by pupen482

2024-03-10 10:11 UTC, xthebat requested changes

2024-03-10 10:11 UTC, xthebat commented on taralo_a/task02/src/main_tree.py
> +        if level == 0 and lvl_mod is True:
`lvl_mod is True` - Найк! :)

2024-03-10 10:11 UTC, xthebat commented on taralo_a/task02/src/main_tree.py
> +            if current_level_nxt == 0 and lvl_mod is True:
lvl_mod is True - Найк! :)

2024-03-10 10:11 UTC, xthebat commented on taralo_a/task02/src/main_tree.py
> +
Зачем пустые строки?

2024-03-10 10:11 UTC, xthebat commented on taralo_a/task02/src/main_tree.py
> +
Лишняя пустая строка, между функциями 2 пустые строки PEP8

2024-03-10 10:11 UTC, xthebat commented on taralo_a/task02/requirements.txt
> +exceptiongroup==1.2.0
Это зачем?

2024-03-10 10:11 UTC, xthebat commented on taralo_a/task02/requirements.txt
> +packaging==23.2
И это?

2024-03-10 10:11 UTC, xthebat commented on taralo_a/task02/requirements.txt
> +iniconfig==2.0.0
А это?

2024-03-10 10:11 UTC, xthebat commented on taralo_a/task02/requirements.txt
> +pluggy==1.4.0
И тут?

2024-03-10 10:11 UTC, xthebat commented on taralo_a/task02/src/main_tree.py
> +    Dirs searching and create list
- О функциях документация обычно пишется в повелительном наклонении.
- Незнание функции должно отражать действие

2024-03-10 10:11 UTC, xthebat commented on taralo_a/task02/src/main_tree.py
> +            else :
Нарушение PEP8

2024-03-10 10:11 UTC, xthebat commented on taralo_a/task02/src/main_tree.py
> +            if symbol == TreeSymbols.T.value :
Можно заменить на тернарный оператор

2024-03-10 10:11 UTC, xthebat commented on taralo_a/task02/src/main_tree.py
> +            tree(path, level=current_level_nxt, prefix=prefix+extension_symbol, lvl_mod=lvl_mod, result=result)
Нарушение PEP8

2024-03-10 10:11 UTC, xthebat commented on taralo_a/task02/src/main_tree.py
> +        print('"{}" does not exist'.format(path_name), file=sys.stderr)
Используйте интерполяцию строк

2024-03-10 10:11 UTC, xthebat commented on taralo_a/task02/test/test_tree.py
> +def test_tree(create_temporary_directory) -> None:
Можно указать аннотацию, которую возвращает фикстура

2024-03-13 05:04 UTC, pupen482 commented on taralo_a/task02/requirements.txt
> +pluggy==1.4.0
видимо это все требуется внутри самого pytest'a..этот  requirements сгенерился автоматически
если убрать все эти либы из окружения, то тест не запускается, вылетают ошибки в модулях самой библиотеке pytest

2024-03-23 12:38 UTC, shadowk1337 approved these changes
Base: 2/3
Color + 1
Sum: 3

2024-03-23 12:39 UTC, merged