novikov_t/task03
xthebat/iu4-2k24-python pull request #62
Opened 2024-03-29 19:33 UTC by SARWX

2024-04-02 15:29 UTC, xthebat requested changes

2024-04-02 15:29 UTC, xthebat commented on novikov_t/task03/src/smd_parse.py
> +    def print_pos(self):
Возможно заменить на приведение к строке?

2024-04-02 15:29 UTC, xthebat commented on novikov_t/task03/src/smd_parse.py
> +    def set_position(self, pos: Vector):
Зачем сеттер без геттера?

2024-04-02 15:29 UTC, xthebat commented on novikov_t/task03/src/smd_parse.py
> +            while not (file.readline().startswith("nodes")):
Вроде бы тут лишние скобки

2024-04-02 15:29 UTC, xthebat commented on novikov_t/task03/src/smd_parse.py
> +                if not (line.startswith("end")):
Лишние скобки после not

2024-04-02 15:29 UTC, xthebat commented on novikov_t/task03/src/smd_parse.py
> +                if not (line.startswith("end")):
Мне кажется if-else лучше инвертировать, тогда код будет более читаемым

2024-04-02 15:29 UTC, xthebat commented on novikov_t/task03/src/smd_parse.py
> +                    node = Node(id=node_id, title=node_title,
Можно в одну строку

2024-04-02 15:29 UTC, xthebat commented on novikov_t/task03/src/smd_parse.py
> +                else:
Кажется, что else не нужен

2024-04-02 15:29 UTC, xthebat commented on novikov_t/task03/src/smd_parse.py
> +            while not (file.readline().startswith("skeleton")):
Скобки не нужны

2024-04-02 15:29 UTC, xthebat commented on novikov_t/task03/src/smd_parse.py
> +            cnt = 0
count

2024-04-02 15:29 UTC, xthebat commented on novikov_t/task03/src/smd_parse.py
> +        with open(self.path, "r") as file:
rt

2024-04-02 15:29 UTC, xthebat commented on novikov_t/task03/src/smd_parse.py
> +        print('skeleton')
нет возможности напечатать в файл

2024-04-02 15:29 UTC, xthebat commented on novikov_t/task03/src/smd_parse.py
> +            while not (file.readline().startswith(f"  time {frame_num}")):
скобки не нужны

2024-04-02 15:29 UTC, xthebat commented on novikov_t/task03/tests/test_smd_parsing.py
> +# from src.smd_parse import generate_tree
мертвый код - убираем

2024-04-02 15:29 UTC, xthebat commented on novikov_t/task03/tests/test_smd_parsing.py
> +        # redirect cout to a file output.smd
Кажется что, неплохо если бы программа сама умела выводить в файл без перенаправления потока :)

2024-04-02 18:23 UTC, SARWX commented on novikov_t/task03/src/smd_parse.py
> +    def set_position(self, pos: Vector):
добавил геттеры

2024-04-02 18:24 UTC, SARWX commented on novikov_t/task03/src/smd_parse.py
> +        print('skeleton')
добавил печать в файл

2024-04-02 18:24 UTC, SARWX commented on novikov_t/task03/tests/test_smd_parsing.py
> +        # redirect cout to a file output.smd
добавил печать в файл

2024-04-02 18:25 UTC, SARWX commented on novikov_t/task03/src/smd_parse.py
> +    def print_pos(self):
заменил

2024-04-02 18:26 UTC, SARWX commented on novikov_t/task03/src/smd_parse.py
> +            while not (file.readline().startswith("nodes")):
убрал

2024-04-02 18:26 UTC, SARWX commented on novikov_t/task03/src/smd_parse.py
> +                if not (line.startswith("end")):
убрал

2024-04-02 18:27 UTC, SARWX commented on novikov_t/task03/src/smd_parse.py
> +                if not (line.startswith("end")):
поменял

2024-04-02 18:27 UTC, SARWX commented on novikov_t/task03/src/smd_parse.py
> +                    node = Node(id=node_id, title=node_title,
переписал

2024-04-02 18:27 UTC, SARWX commented on novikov_t/task03/src/smd_parse.py
> +                else:
убрал

2024-04-02 18:27 UTC, SARWX commented on novikov_t/task03/src/smd_parse.py
> +            while not (file.readline().startswith("skeleton")):
убрал

2024-04-02 18:28 UTC, SARWX commented on novikov_t/task03/src/smd_parse.py
> +            cnt = 0
заменил

2024-04-02 18:28 UTC, SARWX commented on novikov_t/task03/src/smd_parse.py
> +        with open(self.path, "r") as file:
заменил на rt

2024-04-02 18:28 UTC, SARWX commented on novikov_t/task03/src/smd_parse.py
> +            while not (file.readline().startswith(f"  time {frame_num}")):
убрал

2024-04-02 18:28 UTC, SARWX commented on novikov_t/task03/tests/test_smd_parsing.py
> +# from src.smd_parse import generate_tree
убрал

2024-04-13 08:49 UTC, xthebat commented on novikov_t/task03/src/smd_parse.py
> +    "C:\\OTHER\\учеба\\8 семестр\\python\\iu4-2k24-python\\novikov_t\\task03\\animset_t_anims\\a_move_c4_runS.smd")
Надо поправить абсолютный путь

2024-04-13 08:49 UTC, xthebat approved these changes
4

2024-04-21 11:13 UTC, merged