Kokorev_A/Task 03
xthebat/iu4-2k24-python pull request #63
Opened 2024-04-02 09:19 UTC by Casimir-Kepler

2024-04-02 15:38 UTC, xthebat requested changes

2024-04-02 15:38 UTC, xthebat commented on Kokorev_A/task03/src/Task03/animation_parser.py
> +                else:
Кажется, что else не нужен

2024-04-02 15:38 UTC, xthebat commented on Kokorev_A/task03/test/test_parcer.py
> +import pytest
Typo: parser

2024-04-02 15:38 UTC, xthebat commented on Kokorev_A/task03/test/test_parcer.py
> +def test_node_parce():
Typo: parse

2024-04-02 15:38 UTC, xthebat commented on Kokorev_A/task03/test/test_parcer.py
> +def test_frame_parce():
Typo: parse

2024-04-02 15:38 UTC, xthebat commented on Kokorev_A/task03/src/Task03/animations_fixer.py
> +                new_lines[coordinate] = "0.000000"
😑

2024-04-02 15:38 UTC, xthebat commented on Kokorev_A/task03/src/Task03/animation_parser.py
> +    filename = "a_move_c4_walkNE.smd"
Код из if __name__ == "__main__": необходимо перенести в функцию

2024-04-02 15:38 UTC, xthebat commented on Kokorev_A/task03/src/Task03/animation_parser.py
> +class Frame:
Возможно парсинг этих объектов попробовать перенести в их классметоды?

2024-04-03 12:53 UTC, Casimir-Kepler commented on Kokorev_A/task03/src/Task03/animation_parser.py
> +class Frame:
из серии Frame.parce(file)?
Собирать внутри один элемент или сразу весь файл обрабатывать?

2024-04-03 12:53 UTC, Casimir-Kepler commented on Kokorev_A/task03/test/test_parcer.py
> +def test_node_parce():
?

2024-04-03 12:53 UTC, Casimir-Kepler commented on Kokorev_A/task03/test/test_parcer.py
> +import pytest
?

2024-04-03 12:55 UTC, Casimir-Kepler commented on Kokorev_A/task03/src/Task03/animation_parser.py
> +                else:
Да, и так сработает, поправлю

2024-04-03 13:20 UTC, Casimir-Kepler commented on Kokorev_A/task03/src/Task03/animation_parser.py
> +class Frame:
На примере считывания ноды:
![Снимок1](https://github.com/xthebat/iu4-2k24-python/assets/61505735/05ed6525-0a7b-4d66-983c-da13b8ed0890)
![Снимок2](https://github.com/xthebat/iu4-2k24-python/assets/61505735/2c82605a-d041-40b4-842d-03c99a4e901b)

2024-04-03 13:22 UTC, Casimir-Kepler commented on Kokorev_A/task03/src/Task03/animation_parser.py
> +class Frame:
Или со всеми проверками сделать?
![image](https://github.com/xthebat/iu4-2k24-python/assets/61505735/ec0d62dc-ad89-482d-ab65-0058d4cd0a18)

2024-04-03 13:29 UTC, Casimir-Kepler commented on Kokorev_A/task03/src/Task03/animations_fixer.py
> +                new_lines[coordinate] = "0.000000"
Я так понимаю это стоило делать внутри распарсенного документа, а не по быстрому в оперативке?)

2024-04-03 14:01 UTC, Casimir-Kepler commented on Kokorev_A/task03/src/Task03/animation_parser.py
> +    filename = "a_move_c4_walkNE.smd"
Поправил

2024-04-13 08:46 UTC, xthebat requested changes

2024-04-13 08:46 UTC, xthebat commented on Kokorev_A/task03/src/Task03/animation_parser.py
> +class Frame:
Второй вариант

2024-04-13 08:46 UTC, xthebat commented on Kokorev_A/task03/src/Task03/animations_fixer.py
> +                new_lines[coordinate] = "0.000000"
Да, идея в том, что нужно разобрать файл (десериализовать) на классы (в формализованное представление) и потом править его. После чего обратно сериализовать в файлы.

2024-04-13 08:46 UTC, xthebat commented on Kokorev_A/task03/test/test_parcer.py
> +import pytest
Везде нужно поменять parcer/parce (Typo - это не правильно грамматически) на parser/parse.

Чем плохо грамматические ошибки в коде: в большой кодовой базе, может возникать необходимость поиска по именам и если имя написано с ошибкой, то найти будет тяжело

2024-04-17 16:14 UTC, xthebat commented on Kokorev_A/task03/src/Task03/animation_parser.py
> +    nodes = []
**Self-Resolvable**: Добавить аннотацию

2024-04-17 16:16 UTC, xthebat commented on Kokorev_A/task03/src/Task03/animation_parser.py
> +
```python
def size_squared_2d(self):
    return self.position.x * self.position.x + self.position.y * self.position.y
```

2024-04-21 11:01 UTC, merged