Ngo Duy Khanh  task02
xthebat/iu4-2k24-python pull request #69
Opened 2024-04-09 11:33 UTC by khanhbg339

2024-04-13 09:28 UTC, xthebat requested changes

2024-04-13 09:28 UTC, xthebat commented on ngo_d_k/task02/src/task02/task02.py
> +class path_types(Enum):
Нарушение PEP8

2024-04-13 09:28 UTC, xthebat commented on ngo_d_k/task02/src/task02/task02.py
> +class ter_styles(Enum):
Нарушение PEP8

2024-04-13 09:28 UTC, xthebat commented on ngo_d_k/task02/src/task02/task02.py
> +def gener_u_l(
Непонятное имя функции

2024-04-13 09:28 UTC, xthebat commented on ngo_d_k/task02/src/task02/task02.py
> +def gener_inden(lines: List[bool]) -> str:
Для чего это сокращение

2024-04-13 09:28 UTC, xthebat commented on ngo_d_k/task02/src/task02/task02.py
> +def gener_inden(lines: List[bool]) -> str:
Для 3.11 можно не использовать List из typing

2024-04-13 09:28 UTC, xthebat commented on ngo_d_k/task02/src/task02/task02.py
> +def get_p(arguments: List[str]) -> str:
что делает эта фунция

2024-04-13 09:28 UTC, xthebat commented on ngo_d_k/task02/src/task02/task02.py
> +    for dirpaths, dirnames, filenames in os.walk(scan_dir_path):
Для чего for? Если на первом же проходе будет break

2024-04-13 09:28 UTC, xthebat commented on ngo_d_k/task02/src/task02/task02.py
> +) -> List[List]:  # List[[str, bool]]
Зачем эти комменты? Если можно всё это указать в аннотации

2024-04-20 11:21 UTC, khanhbg339 commented on ngo_d_k/task02/src/task02/task02.py
> +class path_types(Enum):
Исправлено

2024-04-20 11:21 UTC, khanhbg339 commented on ngo_d_k/task02/src/task02/task02.py
> +class ter_styles(Enum):
Исправлено

2024-04-20 11:21 UTC, khanhbg339 commented on ngo_d_k/task02/src/task02/task02.py
> +def gener_u_l(
Исправлено

2024-04-20 11:21 UTC, khanhbg339 commented on ngo_d_k/task02/src/task02/task02.py
> +def gener_inden(lines: List[bool]) -> str:
Исправлено

2024-04-20 11:21 UTC, khanhbg339 commented on ngo_d_k/task02/src/task02/task02.py
> +def gener_inden(lines: List[bool]) -> str:
Исправлено

2024-04-20 11:21 UTC, khanhbg339 commented on ngo_d_k/task02/src/task02/task02.py
> +def get_p(arguments: List[str]) -> str:
Исправлено

2024-04-20 11:21 UTC, khanhbg339 commented on ngo_d_k/task02/src/task02/task02.py
> +    for dirpaths, dirnames, filenames in os.walk(scan_dir_path):
Исправлено

2024-04-20 11:21 UTC, khanhbg339 commented on ngo_d_k/task02/src/task02/task02.py
> +) -> List[List]:  # List[[str, bool]]
Исправлено

2024-04-21 11:08 UTC, merged