Task 3
xthebat/iu4-2k24-python pull request #75
Opened 2024-04-14 18:48 UTC by zatryx

Пересоздала, наверное нет смысла уже 1 задание заливать, но могу для статистики если надо (просто не понимаю как отдельный реквест под него сделать)

2024-04-18 15:14 UTC, xthebat requested changes

2024-04-18 15:14 UTC, xthebat commented on Dolgova AV/task 3/task03.py
> +class Timeframe:
в dataclass

2024-04-18 15:14 UTC, xthebat commented on Dolgova AV/task 3/task03.py
> +timeframes = []
Глобальных переменных быть не должно

2024-04-18 15:14 UTC, xthebat commented on Dolgova AV/task 3/task03.py
> +filename = 'a_move_walkW.smd'
Аргумент командной строки\аргумент функции

2024-04-18 15:14 UTC, xthebat commented on Dolgova AV/task 3/task03.py
> +mode = 'waiting'
Константы большими буквами MODE

2024-04-18 15:14 UTC, xthebat commented on Dolgova AV/task 3/task03.py
> +with open(filename, 'r') as file:
Не должно быть кода без функции

2024-04-18 15:14 UTC, xthebat commented on Dolgova AV/task 3/task03.py
> +
Лишние строки

2024-04-18 15:14 UTC, xthebat commented on Dolgova AV/task 3/task03.py
> + 			mode = 'nodes'
Отступы должны быть в 4 пробела

2024-04-18 15:14 UTC, xthebat commented on Dolgova AV/task 3/task03.py
> +			i=0
Нарушение PEP8

2024-04-18 15:14 UTC, xthebat commented on Dolgova AV/task 3/task03.py
> +# блок нодов
Комменты должны быть с табуляцией = коду

2024-04-18 15:14 UTC, xthebat commented on Dolgova AV/task 3/task03.py
> +						timeframe = Timeframe(timestamp,a,b,c,d,e,f,g)
Нарушение PEP8

2024-04-18 15:14 UTC, xthebat commented on Dolgova AV/task 3/task03.py
> +				#print(node)
Нарушение PEP8

2024-04-18 15:14 UTC, xthebat commented on Dolgova AV/task 3/task03.py
> +					a, b, c, d, e, f, g = [word.strip() for word in line.split()]
Не удачные название переменных

2024-04-18 15:14 UTC, xthebat commented on Dolgova AV/task 3/task03.py
> +					a, b, c, d, e, f, g = [word.strip() for word in line.split()]
```python
tokens = [word.strip() for word in line.split()]
timeframe = Timeframe(*tokens)
```

2024-04-18 15:14 UTC, xthebat commented on Dolgova AV/task 3/task03.py
> +nodes = {}
Лучше указывать аннотации к переменным

2024-04-18 17:27 UTC, zatryx commented
Если что коммит с кодом называется d, я случайно :')
Не знаю как видео удобнее, есть еще на ютубе https://youtu.be/N3PApkUfbkk

2024-04-21 11:00 UTC, zatryx commented on Dolgova AV/task 3/task03.py
> +
вроде все удалила, только 79-70 строки мне автоформат в pycharm вставляет, их оставила

2024-04-21 11:10 UTC, merged